edited Ceda ivt
galasa-dev/managers pull request #382
Opened 2020-11-27 09:47 UTC by DianaSlepikaite

Signed-off-by: Diana Slepikaite <d.slepikaite@gmail.com>

2020-11-27 10:00 UTC, Michael-Baylis approved these changes

2020-11-27 10:01 UTC, Michael-Baylis submitted a review, later dismissed

2020-11-27 12:17 UTC, hobbit1983 approved these changes

2020-11-30 20:41 UTC, hobbit1983 requested changes
Just a small request - you provision a Logger object in the test but never use it.  Please either log something to the run log, or don't provision the logger.

2020-12-01 12:00 UTC, hobbit1983 approved these changes

2020-12-01 12:01 UTC, merged