Interfaces for docker volumes
galasa-dev/managers pull request #397
Opened 2020-12-11 13:06 UTC by Jimbo4794

Signed-off-by: James Davies <jdavies47@hotmail.co.uk>

2020-12-11 13:37 UTC, Jimbo4794 commented
Will fix the defaulting error upon implementation

2020-12-14 13:36 UTC, Michael-Baylis requested changes
I don't see what these volumes gives the test from these interfaces.   What is the point of creating a volume?????
Docker containers do need a volume to operate, even if defined in the Dockerfile.  The reason for the volume would be to share across containers and to preserve data after a container is removed.
Think you need to ask the enhancement requestor for the reasons behind the request.

2020-12-14 13:36 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.docker.manager/src/main/java/dev/galasa/docker/DockerContainer.java
> +    public String volumes();
Should be an array of Strings at the very least.
Actually,   the volumes should be an array of DockerVolume annotations. with the volumename and the path as invidual strings.
You will need to indicate that the volume will be prefixed with the container/runname to ensure the volume names do not clash with other test runs

2020-12-14 13:36 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.docker.manager/src/main/java/dev/galasa/docker/IDockerVolume.java
> +    public JsonObject getMountJson() throws DockerManagerException;
Dont return the JSON.   Return a parsed structure to insulate the tester from changes to the docker engine.
Only provide the variables that you think the tester needs to know.

2020-12-14 13:37 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.docker.manager/src/main/java/dev/galasa/docker/DockerContainer.java
> +    public String volumes();
prefixed with GALASA_runname_,  leave the containername off of it incase the volume is shared across containers.
GALASA being the same prefix as the containers

2021-01-18 09:25 UTC, Jimbo4794 commented
No longer relevant

2021-01-18 09:25 UTC, closed without merging