TextScannerImpl with Junit
galasa-dev/managers pull request #403
Opened 2020-12-22 11:53 UTC by DianaSlepikaite

Signed-off-by: Diana Slepikaite <d.slepikaite@gmail.com>

2020-12-23 13:54 UTC, DianaSlepikaite commented
rerun tests

2021-01-14 13:09 UTC, Michael-Baylis requested changes
Sorry,  need some work,  especially the possibility of double accounting on the inputstream
I will knock up a text file and call to illustrate

2021-01-14 13:09 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +			if(queue.isAtFullCapacity()) {
simplify the code,  you don't have to wait for the queue to fill before you start checking

2021-01-14 13:09 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +				toScan ="";
Use StringBuffer to build the string to scan

2021-01-14 13:09 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +				Matcher m = searchPattern.matcher(toScan);
Have to be extremely careful here.   as the found text moves up the fifo queue,  you could be double accounting the found text and finding more occurenances than there actually is.

2021-01-14 13:09 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +		if (lines<10) {
dont need this if you start the above from input line 1

2021-01-14 13:09 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +		while((line =reader.readLine())!=null) {
same issues here as in the scan method.   you should be able to use the same code for both.

2021-01-14 13:09 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/test/resources/loremIpsum.txt
> +Lorem ipsum dolor sit amet, consectetur adipiscing elit.
Ok,  this isn't working,   I can't validate the junit tests.   Would you please simplify the input text with stuff like
Line 1
Line 2
Line 3 Match 1
etc

2021-01-22 10:25 UTC, DianaSlepikaite commented
rerun tests

2021-01-22 12:01 UTC, Michael-Baylis requested changes
The method needs a big clean up and rework for readability and maintainability reasons

2021-01-22 12:01 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +							}
should check at this point if count is matched and return.

2021-01-22 12:01 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +		}else if(found>0&&found<count) {
dont need any of this if checked earlier

2021-01-22 12:01 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.textscan.manager/src/main/java/dev/galasa/textscan/spi/TextScannerImpl.java
> +			throw new MissingTextException("Search Pattern '"+searchPattern+"' was not found");
this is all you need at the end of the loop

2021-01-25 13:45 UTC, DianaSlepikaite commented
rerun tests

2021-01-26 09:11 UTC, DianaSlepikaite commented
rerun tests

2021-01-26 13:44 UTC, DianaSlepikaite commented
rerun tests

2021-01-26 15:33 UTC, Michael-Baylis approved these changes

2021-01-26 15:57 UTC, merged