Docker ports added to config for containers
galasa-dev/managers pull request #417
Opened 2021-02-10 19:33 UTC by Jimbo4794

2021-02-10 19:41 UTC, Jimbo4794 commented
rerun tests

2021-02-12 09:21 UTC, Michael-Baylis requested changes

2021-02-12 09:21 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-cloud-parent/dev.galasa.docker.manager/src/main/java/dev/galasa/docker/IDockerContainerConfig.java
> +    public void setExposedPorts(List<String> ports);
Exposed ports need 1 or 2 port numbers,    the one for the host system and the one in the container.   ie 8080/tcp->80/tcp
You will need to implement it properly I am afraid.

2021-02-15 11:06 UTC, Michael-Baylis approved these changes

2021-02-18 08:29 UTC, merged