Initial commit for eclipse manager and interfaces
galasa-dev/managers pull request #657
Opened 2021-08-26 14:32 UTC by ReeceWilliams1105

Signed-off-by: Reece Williams <reecewilliams1105@gmail.com>

2021-09-02 10:04 UTC, Michael-Baylis requested changes
as discussion on Slack

2021-09-02 17:12 UTC, ReeceWilliams1105 commented
I think there is a chance that I have missed some of the changes requested however this should be the vast majority of them.

2021-09-06 12:32 UTC, Michael-Baylis requested changes

2021-09-06 12:32 UTC, Michael-Baylis commented on galasa-managers-parent/galasa-managers-testingtools-parent/dev.galasa.eclipse.runtime.manager/bnd.bnd
> +-snapshot: ${tstamp}
The projects are still called dev.galasa.eclipse.runtime,    needs to be dev.galasa.eclipseruntime

2021-09-06 13:42 UTC, closed without merging