Add Alter Sit to SemCICSImpl
galasa-dev/managers pull request #792
Opened 2022-07-25 21:38 UTC by lewisja1406

Please review alter sit code for Galasa conversion

2022-07-25 21:40 UTC, lewisja1406 commented
@hobbit1983 Please review changes

2022-07-26 07:59 UTC, hobbit1983 requested changes
Nothing major - just some comment clean up and spellings - Think I got most of the reviewing done when we buddied through this yesterday.  Nice to see alterSIT making it's way into Galasa!

2022-07-26 07:59 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/build.gradle
> +version = '0.25.0'
Is there the equivalent of a release.yaml to incorporate this into the internal bom?

2022-07-26 07:59 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/src/main/java/dev/galasa/sem/internal/SemCicsImpl.java
> +		}
can we isolate this try catch to just the line of code that could throw an exception if possible

2022-07-26 07:59 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/src/main/java/dev/galasa/sem/internal/SemCicsImpl.java
> +        		Sit sitOverride = new Sit(sitParam, sitValue, "Overriden during runtime");
I 'think' there are two 'd' in Overridden - I know picky picky

2022-07-26 07:59 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/src/main/java/dev/galasa/sem/internal/SemCicsImpl.java
> +     * and activate the APPID of the CICS job. Store the JCL
APPLID

2022-07-26 07:59 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/src/main/java/dev/galasa/sem/internal/SemCicsImpl.java
> +			String runtimeJcl = semZosHandler.generateJCL(job);
it's not skeleton in the same way we use the term in artefact manager - can you just have a quick look at what this method does and amend the comment please

2022-07-26 10:36 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/build.gradle
> +version = '0.25.0'
I see you have updated

2022-07-26 10:37 UTC, hobbit1983 approved these changes

2022-07-28 08:22 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-internal-parent/dev.galasa.sem.manager/src/main/java/dev/galasa/sem/internal/SemCicsImpl.java
> +       	}
There is a concern here that if we wanted to test what happened if you tried to start a CICS without these parameters we might have a problem, but I think we are OK

2022-07-28 08:23 UTC, hobbit1983 approved these changes

2022-07-28 08:39 UTC, merged