z/OS port provisioning and resource monitoring for ports
galasa-dev/managers pull request #800
Opened 2022-08-15 15:49 UTC by lewisja1406

This is specifically to z/OS at the moment. It will need abstracting for generic ports.

2022-08-16 15:04 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosManagerImpl.java
> +			e.printStackTrace();
need to re-throw an exception

2022-08-16 15:04 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosManagerImpl.java
>          return this.zosConnectInstallDir;
zosConnect????

2022-08-16 15:05 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPoolPorts.java
> +		List<String> resourceStrings = PoolPorts.get(image);
what happens if there are no resource strings for this image?

2022-08-16 15:06 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPoolPorts.java
> +			List<String> zosPorts = this.rps.obtainResources(resourceStrings, null, 1, 1, dss, "zosport");
if this is empty after the call to obtain resources then thePort will be returned as null

2022-08-16 15:08 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosResourceManagement.java
> +				this.framework.getRandom().nextInt(20), 20, TimeUnit.SECONDS);
point for discussion - should the timeout be configurable through the CPS?

2022-08-17 08:46 UTC, lewisja1406 commented
Review changes made please re-review

2022-08-17 09:07 UTC, Jimbo4794 requested changes

2022-08-17 09:07 UTC, Jimbo4794 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPortResourceMonitor.java
> +			for (String prefix : zosPortsInDss.keySet()) {
its a key not prefix

2022-08-17 09:07 UTC, Jimbo4794 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPortResourceMonitor.java
> +					logger.info("Found inactive run " + removeRun + ". Freeing port " + removePort);
Dont message about the run, not your job, message youve found a dirty port on image X

2022-08-17 09:07 UTC, Jimbo4794 commented on galasa-managers-parent/galasa-managers-zos-parent/dev.galasa.zos.manager/src/main/java/dev/galasa/zos/internal/ZosPortResourceMonitor.java
> +	public void runFinishedOrDeleted(String runName) {
Any similiar above change for this too

2022-08-17 09:32 UTC, hobbit1983 approved these changes

2022-08-17 09:59 UTC, lewisja1406 commented
@Jimbo4794 Please can you re-review based on the changes. I have tested and things look good

2022-08-17 14:07 UTC, Jimbo4794 approved these changes

2022-08-17 14:18 UTC, merged