Iss815
galasa-dev/managers pull request #816
Opened 2022-10-13 13:06 UTC by KirbyKatcher

2022-10-14 09:13 UTC, hobbit1983 requested changes

2022-10-14 09:13 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-core-parent/dev.galasa.core.manager/src/main/java/dev/galasa/core/manager/internal/CoreManagerImpl.java
> +	}
Don't we need to return the cred object back to the caller?

2022-10-14 09:15 UTC, hobbit1983 commented
Manually set DCO to pass - KirbyKatcher is new to Galasa team and this code is fine to be delivered under the EPLv2 License

2022-10-14 10:25 UTC, hobbit1983 approved these changes

2022-11-10 17:03 UTC, hobbit1983 commented
@KirbyKatcher any reason why we haven't merged this yet?

2022-11-11 08:58 UTC, galasa-team commented
Build successful

2022-11-11 09:04 UTC, merged

2022-11-11 09:06 UTC, KirbyKatcher commented
No reason, merged now