fix error scenario issues + typos
galasa-dev/managers pull request #882
Opened 2023-06-20 17:19 UTC by Mark-J-Lawrence

I've been experiencing a persistent problem whilst developing the SDV manager where 50% of runs would fail, I decided to have a dig into it today.

I'm probably doing something considered bad practice, but either way, Galasa shouldn't break doing it:

```
try {
     region.ceda().deleteGroup(terminal, "SRRGRP");
} catch (CedaException e) {}
			
region.ceda().createResource(terminal, "JOURNALMODEL", "SRR", "SRRGRP", "JOURNALNAME(DFHSECR) DESCRIPTION(SRR JOURNAL) TYPE(MVS) STREAMNAME(MLAWR." + region.getApplid() + ".DFHSECR)");
region.ceda().installGroup(terminal, "SRRGRP");
```

Depending on the scenario, the `SRRGRP` may or may not exist when running this code. If it does exist, then things behave, if it doesn't, it causes a `DELETE UNSUCCESSFUL` message, which causes a different code path to be taken in the CEDA helper.
I found that when debugging, everything worked fine, it would only fail when letting the code blitz though, the `createResource` function would fail trying to reset the screen. It whiffed of a timing issue.

Looking at the code, there were function presses one after another, without waiting inbetween to check the terminal was ready for the next input, I dropped a `wfk()` and everything started working reliably.

I found there were a few places in the CEDA helper than needed this, plus it was a bit messy with lots of switching between the use of `wfk()` and `waitForKeyboard()`, so I've standardised it throughout and made it a bit clearer. I also fixed two typos.

Let me know if these widespread changes aren't suitable & I'll reduce to just the fix that stops my code breaking.
I've tested my code path thoroughly now though, and its resolved.

2023-06-20 17:20 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2023-06-20 17:22 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2023-06-20 19:00 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2023-06-21 09:34 UTC, hobbit1983 requested changes
Actual code change is fine.  However the versioning of the manager in the build.gradle and the release.yaml need to reflect 0.29.0

2023-06-21 09:34 UTC, hobbit1983 commented on galasa-managers-parent/galasa-managers-cicsts-parent/dev.galasa.cicsts.ceda.manager/build.gradle
> +version = '0.22.0'
Needs to be bumped to 0.29.0

2023-06-21 09:34 UTC, hobbit1983 commented on release.yaml
> +    version: 0.22.0
Needs to reference 0.29.0

2023-06-21 10:03 UTC, Mark-J-Lawrence commented on release.yaml
> +    version: 0.22.0
Thanks @hobbit1983, now updated 👍

2023-06-21 10:04 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2023-06-21 10:04 UTC, galasa-team commented
Automatic triggering of the build is cancelled as user is not a member of the approved groups. Please ask an admin to review this PR and create a comment on the PR stating 'Approved for building'

2023-06-21 10:14 UTC, hobbit1983 approved these changes
Approved for building

2023-06-21 10:23 UTC, galasa-team commented
Build successful

2023-06-21 11:26 UTC, hobbit1983 commented
@Mark-J-Lawrence All ready for merging

2023-06-21 11:31 UTC, Mark-J-Lawrence commented
@hobbit1983 I don't have a `Merge` button, I'm guessing because I'm not a member of the GH galasa team

2023-06-21 11:33 UTC, hobbit1983 commented
Sorry

2023-06-21 11:34 UTC, merged

2023-06-21 11:34 UTC, hobbit1983 commented
Done

2023-06-21 11:38 UTC, Mark-J-Lawrence commented
Thanks @hobbit1983! 👍