fix null creds object
galasa-dev/managers pull request #999
Opened 2024-10-08 16:13 UTC by Mark-J-Lawrence

Adding fix for recently found problem in IVT where creds object was null, but error wasn't being raised.

2024-10-08 16:15 UTC, Mark-J-Lawrence commented
@jadecarino Adding this fix now, as its an easy one.....the fix for the SEC=NO issue is a bit more involved so I'll deliver that separately

2024-10-10 12:40 UTC, jadecarino approved these changes

2024-10-10 12:41 UTC, jadecarino requested changes
These changes look good - please can you update the version of the SDV manager?

2024-10-10 13:00 UTC, jadecarino approved these changes

2024-10-10 13:00 UTC, merged